name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version:  24.x
      - run: npm install
      - run: npm run lint
      - run: npm test
        env:
          SWITCHER_API_KEY: ${{ secrets.SWITCHER_API_KEY }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: env.SONAR_TOKEN != ''

  build-test:
    name: Build & Test - Node ${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Build & Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm test
        env:
          SWITCHER_API_KEY: ${{ secrets.SWITCHER_API_KEY }}
